package settings

import (
	"fmt"
	"strings"
)

// RenderCollectorConfig generates a collector-config.yaml from the current
// provider settings. Secrets are referenced as ${ENV_VAR} placeholders —
// the OTel Collector expands these from the process environment at startup.
func RenderCollectorConfig(s *ProviderSettings, dsn string) string {
	var b strings.Builder

	b.WriteString("# Cloud Security Fabric — Collector Pipeline Configuration\n")
	b.WriteString("# Auto-generated by CSF API. Edit via the Settings UI.\n\n")

	// --- Receivers ---
	b.WriteString("receivers:\n")
	b.WriteString("  otlp:\n")
	b.WriteString("    protocols:\n")
	b.WriteString("      grpc:\n")
	b.WriteString("        endpoint: 0.0.0.0:4317\n")
	b.WriteString("      http:\n")
	b.WriteString("        endpoint: 0.0.0.0:4318\n")

	if s.AWS.Enabled {
		b.WriteString("\n  awssechub:\n")
		fmt.Fprintf(&b, "    region: %s\n", s.AWS.Region)
		fmt.Fprintf(&b, "    poll_interval: %s\n", s.AWS.PollInterval)
		fmt.Fprintf(&b, "    batch_size: %d\n", s.AWS.BatchSize)
		if s.AWS.AssumeRole != "" {
			fmt.Fprintf(&b, "    assume_role: %q\n", s.AWS.AssumeRole)
		}
		if s.AWS.ExternalID != "" {
			fmt.Fprintf(&b, "    external_id: %q\n", s.AWS.ExternalID)
		}
		if len(s.AWS.SeverityLabels) > 0 || s.AWS.RecordState != "" {
			b.WriteString("    filters:\n")
			if len(s.AWS.SeverityLabels) > 0 {
				fmt.Fprintf(&b, "      severity_labels: [%s]\n", strings.Join(s.AWS.SeverityLabels, ", "))
			}
			if s.AWS.RecordState != "" {
				fmt.Fprintf(&b, "      record_state: %s\n", s.AWS.RecordState)
			}
		}
	}

	if s.GitHub.Enabled {
		b.WriteString("\n  githubghas:\n")
		fmt.Fprintf(&b, "    owner: %s\n", s.GitHub.Owner)
		if len(s.GitHub.Repos) > 0 {
			fmt.Fprintf(&b, "    repos: [%s]\n", strings.Join(s.GitHub.Repos, ", "))
		}
		if s.GitHub.AuthMethod == "app" {
			fmt.Fprintf(&b, "    app_id: %d\n", s.GitHub.AppID)
			fmt.Fprintf(&b, "    app_installation_id: %d\n", s.GitHub.AppInstallationID)
			fmt.Fprintf(&b, "    app_private_key: ${%s}\n", SecretGitHubAppPrivateKey)
		} else {
			fmt.Fprintf(&b, "    token: ${%s}\n", SecretGitHubToken)
		}
		fmt.Fprintf(&b, "    poll_interval: %s\n", s.GitHub.PollInterval)
		fmt.Fprintf(&b, "    enable_code_scanning: %t\n", s.GitHub.EnableCodeScanning)
		fmt.Fprintf(&b, "    enable_dependabot: %t\n", s.GitHub.EnableDependabot)
		fmt.Fprintf(&b, "    enable_secret_scanning: %t\n", s.GitHub.EnableSecretScanning)
		if s.GitHub.APIURL != "" {
			fmt.Fprintf(&b, "    api_url: %q\n", s.GitHub.APIURL)
		}
	}

	if s.GCP.Enabled {
		b.WriteString("\n  gcpscc:\n")
		if s.GCP.ScopeType == "organization" && s.GCP.OrganizationID != "" {
			fmt.Fprintf(&b, "    organization_id: %q\n", s.GCP.OrganizationID)
		} else if s.GCP.ProjectID != "" {
			fmt.Fprintf(&b, "    project_id: %q\n", s.GCP.ProjectID)
		}
		fmt.Fprintf(&b, "    poll_interval: %s\n", s.GCP.PollInterval)
		fmt.Fprintf(&b, "    credentials_file: ${%s}\n", SecretGCPCredentials)
		if len(s.GCP.Sources) > 0 {
			fmt.Fprintf(&b, "    sources: [%s]\n", strings.Join(s.GCP.Sources, ", "))
		}
	}

	if s.Azure.Enabled {
		b.WriteString("\n  azuredefender:\n")
		fmt.Fprintf(&b, "    subscription_id: %q\n", s.Azure.SubscriptionID)
		fmt.Fprintf(&b, "    tenant_id: %q\n", s.Azure.TenantID)
		if s.Azure.ClientID != "" {
			fmt.Fprintf(&b, "    client_id: %q\n", s.Azure.ClientID)
		}
		fmt.Fprintf(&b, "    client_secret: ${%s}\n", SecretAzureClientSecret)
		fmt.Fprintf(&b, "    poll_interval: %s\n", s.Azure.PollInterval)
	}

	// --- Processors ---
	b.WriteString("\nprocessors:\n")
	b.WriteString("  batch:\n")
	b.WriteString("    send_batch_size: 256\n")
	b.WriteString("    timeout: 5s\n")
	b.WriteString("\n  memory_limiter:\n")
	b.WriteString("    check_interval: 1s\n")
	b.WriteString("    limit_mib: 512\n")
	b.WriteString("    spike_limit_mib: 128\n")
	b.WriteString("\n  ocsftransform:\n")
	b.WriteString("    enrich_epss: false\n")
	b.WriteString("    enrich_kev: false\n")
	b.WriteString("    csf_extensions: true\n")

	// --- Exporters ---
	b.WriteString("\nexporters:\n")
	b.WriteString("  agegraph:\n")
	fmt.Fprintf(&b, "    dsn: %q\n", dsn)
	b.WriteString("    graph_name: security_fabric\n")
	b.WriteString("    batch_size: 100\n")
	b.WriteString("    flush_interval: 10s\n")
	b.WriteString("\n  debug:\n")
	b.WriteString("    verbosity: basic\n")

	// --- Extensions ---
	b.WriteString("\nextensions:\n")
	b.WriteString("  zpages:\n")
	b.WriteString("    endpoint: 0.0.0.0:55679\n")

	// --- Service / pipelines ---
	b.WriteString("\nservice:\n")
	b.WriteString("  extensions: [zpages]\n")
	b.WriteString("  pipelines:\n")
	b.WriteString("    logs/security:\n")

	receivers := []string{"otlp"}
	if s.AWS.Enabled {
		receivers = append(receivers, "awssechub")
	}
	if s.GitHub.Enabled {
		receivers = append(receivers, "githubghas")
	}
	if s.GCP.Enabled {
		receivers = append(receivers, "gcpscc")
	}
	if s.Azure.Enabled {
		receivers = append(receivers, "azuredefender")
	}
	fmt.Fprintf(&b, "      receivers: [%s]\n", strings.Join(receivers, ", "))
	b.WriteString("      processors: [memory_limiter, batch, ocsftransform]\n")
	b.WriteString("      exporters: [agegraph, debug]\n")
	b.WriteString("  telemetry:\n")
	b.WriteString("    logs:\n")
	b.WriteString("      level: info\n")
	b.WriteString("    metrics:\n")
	b.WriteString("      address: 0.0.0.0:8888\n")

	return b.String()
}
