apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "csf.fullname" . }}-api
  labels:
    {{- include "csf.componentFullLabels" (dict "component" "api" "context" .) | nindent 4 }}
spec:
  replicas: {{ .Values.api.replicas }}
  selector:
    matchLabels:
      {{- include "csf.componentLabels" (dict "component" "api" "context" .) | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "csf.componentLabels" (dict "component" "api" "context" .) | nindent 8 }}
    spec:
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: api
          image: "{{ .Values.api.image.repository }}:{{ .Values.api.image.tag }}"
          imagePullPolicy: {{ .Values.global.imagePullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.api.port }}
              protocol: TCP
          env:
            - name: CSF_DB_HOST
              value: {{ include "csf.fullname" . }}-postgresql
            - name: CSF_DB_PORT
              value: {{ .Values.postgresql.port | quote }}
            - name: CSF_DB_NAME
              value: {{ .Values.postgresql.credentials.database }}
            - name: CSF_DB_USER
              value: {{ .Values.postgresql.credentials.username }}
            - name: CSF_DB_PASSWORD
              value: {{ .Values.postgresql.credentials.password }}
            - name: CSF_DB_DSN
              value: {{ include "csf.postgresqlDSN" . | quote }}
            - name: CSF_GRAPH_NAME
              value: {{ .Values.postgresql.credentials.graphName }}
            - name: CSF_LISTEN_ADDR
              value: "0.0.0.0:{{ .Values.api.port }}"
          {{- with .Values.api.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.api.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.api.resources | nindent 12 }}
      {{- with .Values.api.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.api.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.api.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
