apiVersion: v1
kind: Service
metadata:
  name: {{ include "csf.fullname" . }}-api
  labels:
    {{- include "csf.componentFullLabels" (dict "component" "api" "context" .) | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: {{ .Values.api.port }}
      targetPort: http
      protocol: TCP
  selector:
    {{- include "csf.componentLabels" (dict "component" "api" "context" .) | nindent 4 }}
