apiVersion: v1
kind: Service
metadata:
  name: {{ include "csf.fullname" . }}-collector
  labels:
    {{- include "csf.componentFullLabels" (dict "component" "collector" "context" .) | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: otlp-grpc
      port: {{ .Values.collector.ports.otlpGrpc }}
      targetPort: otlp-grpc
      protocol: TCP
    - name: otlp-http
      port: {{ .Values.collector.ports.otlpHttp }}
      targetPort: otlp-http
      protocol: TCP
    - name: health
      port: {{ .Values.collector.ports.health }}
      targetPort: health
      protocol: TCP
  selector:
    {{- include "csf.componentLabels" (dict "component" "collector" "context" .) | nindent 4 }}
